# Generated by Django 3.2 on 2021-04-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_category',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_name',
            field=models.TextField(default='Not Specified'),
        ),
    ]
