# Generated by Django 3.2 on 2021-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210410_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shop_category',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shop_name',
            field=models.CharField(default='Not Specified', max_length=50),
        ),
    ]
