# Generated by Django 3.2 on 2021-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_alter_bills_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
