# Generated by Django 3.2 on 2021-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0003_alter_bills_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(),
        ),
    ]
